language: node_js
node_js:
  - 0.12
env:
  global:
  - BS_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
  - BS_AUTOMATE_BUILD="Travis build No. $TRAVIS_BUILD_NUMBER for $TRAVIS_REPO_SLUG"
  matrix:
  - SELENIUM_PLATFORM=WINDOWS SELENIUM_BROWSER=IE SELENIUM_VERSION=9